### PR TITLE
GUI configuration tool

### PR DESCRIPTION
**Pull request by mireq**
GUI configuration tool is very useful. My branch contains fixes to enable config tool.

qt_config

### CODE REVIEW

**Comment by hazel-bunny** [comment]
Tried to build for Qt6 using your branch with USE_GUI_CONFIG set to OFF, but
```
$ make
[  2%] Automatic MOC for target skulpture
[  2%] Built target skulpture_autogen
[  5%] Building CXX object src/CMakeFiles/skulpture.dir/skulpture_autogen/mocs_compilation.cpp.o
[  8%] Building CXX object src/CMakeFiles/skulpture.dir/sk_animations.cpp.o
[ 11%] Building CXX object src/CMakeFiles/skulpture.dir/sk_arrows.cpp.o
[ 14%] Building CXX object src/CMakeFiles/skulpture.dir/sk_buttons.cpp.o
[ 17%] Building CXX object src/CMakeFiles/skulpture.dir/sk_cache.cpp.o
[ 20%] Building CXX object src/CMakeFiles/skulpture.dir/sk_color.cpp.o
[ 23%] Building CXX object src/CMakeFiles/skulpture.dir/sk_combobox.cpp.o
[ 26%] Building CXX object src/CMakeFiles/skulpture.dir/sk_complex.cpp.o
[ 29%] Building CXX object src/CMakeFiles/skulpture.dir/sk_dial.cpp.o
[ 32%] Building CXX object src/CMakeFiles/skulpture.dir/sk_dock.cpp.o
[ 35%] Building CXX object src/CMakeFiles/skulpture.dir/sk_factory.cpp.o
[ 38%] Building CXX object src/CMakeFiles/skulpture.dir/sk_frames.cpp.o
[ 41%] Building CXX object src/CMakeFiles/skulpture.dir/sk_gradients.cpp.o
[ 44%] Building CXX object src/CMakeFiles/skulpture.dir/sk_header.cpp.o
[ 47%] Building CXX object src/CMakeFiles/skulpture.dir/sk_icons.cpp.o
[ 50%] Building CXX object src/CMakeFiles/skulpture.dir/sk_layout.cpp.o
/home/[REDACTED]/src/test/skulpture/src/sk_layout.cpp: In member function ‘virtual int SkulptureStyle::pixelMetric(QStyle::PixelMetric, const QStyleOption*, const QWidget*) const’:
/home/[REDACTED]/src/test/skulpture/src/sk_layout.cpp:212:14: error: ‘PM_DefaultTopLevelMargin’ was not declared in this scope
  212 |         case PM_DefaultTopLevelMargin: {
      |              ^~~~~~~~~~~~~~~~~~~~~~~~
/home/[REDACTED]/src/test/skulpture/src/sk_layout.cpp:218:14: error: ‘PM_DefaultChildMargin’ was not declared in this scope
  218 |         case PM_DefaultChildMargin: {
      |              ^~~~~~~~~~~~~~~~~~~~~
/home/[REDACTED]/src/test/skulpture/src/sk_layout.cpp:224:14: error: ‘PM_DefaultLayoutSpacing’ was not declared in this scope
  224 |         case PM_DefaultLayoutSpacing: {
      |              ^~~~~~~~~~~~~~~~~~~~~~~
/home/[REDACTED]/src/test/skulpture/src/sk_layout.cpp:283:42: error: ‘PM_DefaultChildMargin’ is not a member of ‘QStyle’
  283 |             PixelMetric metric = QStyle::PM_DefaultChildMargin;
      |                                          ^~~~~~~~~~~~~~~~~~~~~
/home/[REDACTED]/src/test/skulpture/src/sk_layout.cpp:285:34: error: ‘PM_DefaultTopLevelMargin’ is not a member of ‘QStyle’
  285 |                 metric = QStyle::PM_DefaultTopLevelMargin;
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/skulpture.dir/build.make:286: src/CMakeFiles/skulpture.dir/sk_layout.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:99: src/CMakeFiles/skulpture.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by hazel-bunny** [comment]
Looks like PM_DefaultTopLevelMargin, PM_DefaultChildMargin and PM_DefaultLayoutSpacing were deprecated in Qt 5.15 and are removed in Qt 6

**Comment by hazel-bunny** [comment]
Also generates some warnings in Qt 5
```
[REDACTED]/BUILD/skulpture-0cbe7aad8fb882a14ef832f927cbe82aeebb038c/src/sk_layout.cpp: In member function 'virtual int SkulptureStyle::pixelMetric(QStyle::PixelMetric, const QStyleOption*, const QWidget*) const':
[REDACTED]/BUILD/skulpture-0cbe7aad8fb882a14ef832f927cbe82aeebb038c/src/sk_layout.cpp:62:12: warning: enumeration value 'PM_TitleBarButtonIconSize' not handled in switch [-Wswitch]
   62 |     switch (metric) {
      |            ^
[REDACTED]/BUILD/skulpture-0cbe7aad8fb882a14ef832f927cbe82aeebb038c/src/sk_layout.cpp:62:12: warning: enumeration value 'PM_TitleBarButtonSize' not handled in switch [-Wswitch]
[REDACTED]/BUILD/skulpture-0cbe7aad8fb882a14ef832f927cbe82aeebb038c/src/sk_layout.cpp: In member function 'virtual QRect SkulptureStyle::subElementRect(QStyle::SubElement, const QStyleOption*, const QWidget*) const':
[REDACTED]/BUILD/skulpture-0cbe7aad8fb882a14ef832f927cbe82aeebb038c/src/sk_layout.cpp:611:12: warning: enumeration value 'SE_DialogButtonBoxLayoutItem' not handled in switch [-Wswitch]
  611 |     switch (element) {
      |            ^
[REDACTED]/BUILD/skulpture-0cbe7aad8fb882a14ef832f927cbe82aeebb038c/src/sk_layout.cpp:611:12: warning: enumeration value 'SE_TabBarScrollLeftButton' not handled in switch [-Wswitch]
[REDACTED]/BUILD/skulpture-0cbe7aad8fb882a14ef832f927cbe82aeebb038c/src/sk_layout.cpp:611:12: warning: enumeration value 'SE_TabBarScrollRightButton' not handled in switch [-Wswitch]
[REDACTED]/BUILD/skulpture-0cbe7aad8fb882a14ef832f927cbe82aeebb038c/src/sk_layout.cpp:611:12: warning: enumeration value 'SE_TabBarTearIndicatorRight' not handled in switch [-Wswitch]
[REDACTED]/BUILD/skulpture-0cbe7aad8fb882a14ef832f927cbe82aeebb038c/src/sk_layout.cpp:611:12: warning: enumeration value 'SE_PushButtonBevel' not handled in switch [-Wswitch]
```

**Comment by atolstoy** [comment]
I've tested your branch on Tumbleweed and got the following results:
- the Qt5 version builds OK with the only slight automoc warning:
```
AutoMoc warning
---------------
"SRC:/src/config/sk_config.cpp"
includes the moc file "sk_config.moc", but does not contain a Q_OBJECT, Q_GADGET, Q_NAMESPACE, Q_NAMESPACE_EXPORT, K_PLUGIN_FACTORY, K_PLUGIN_CLASS, K_PLUGIN_FACTORY_WITH_JSON or K_PLUGIN_CLASS_WITH_JSON macro.

AutoMoc: /home/atolstoy/Sources/skulpture/src/config/sk_config.cpp:0: Note: No relevant classes found. No output generated.
```
- However, no GUI config can be found in kcm settings. I tried explicitly casting `cmake -DUSE_GUI_CONFIG=ON ..` with out luck.
- Cannot build the Qt6 version:
```
Qt version - 6
-- Configuring done (0.2s)
CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt5::Core" does
not agree with the value of QT_MAJOR_VERSION already determined
for "kstyle_skulpture_config".
```

Please comment on this.

**Comment by mireq** [comment]
I will fix Qt6 build today.

Config tool (kstyle_skulpture_config) needs to be installed in Qt plugin directory (/usr/lib64/qt5/plugins/kstyle_skulpture_config.so on my machine) and skulptureui.rc in kxmlgui5 directory (/usr/share/kxmlgui5/skulpture/skulptureui.rc).

**Comment by mireq** [comment]
Qt6 version with USE_GUI_CONFIG=Off now works. I don't have KDE built wth Qt6, so i can't test config tool with Qt6.

**Comment by mireq** [comment]
@atolstoy i have added missing rc file to install install targets. Configuration tool should now work (tested using Qt 5.15, KDE 5.106.0).

**Comment by atolstoy** [comment]
> @atolstoy i have added missing rc file to install install targets. Configuration tool should now work (tested using Qt 5.15, KDE 5.106.0).

I can prove it really works. Thanks!

**Pull request merged**
